import type { Lead, Task, Activity, User } from "@/types";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);
const hoursAgo = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);

export const MOCK_USERS: User[] = [
  { id: "demo-manager", email: "della@mallardmortgages.co.uk", fullName: "Della Mallard", phone: "+44 114 000 0001", role: "manager", avatarUrl: null, isActive: true, createdAt: daysAgo(90) as never },
  { id: "demo-sales", email: "alex@mallardmortgages.co.uk", fullName: "Alex Rivera", phone: "+44 114 000 0002", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(60) as never },
  { id: "user-3", email: "priya@mallardmortgages.co.uk", fullName: "Priya Patel", phone: "+44 114 000 0003", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(45) as never },
  { id: "user-4", email: "tom@mallardmortgages.co.uk", fullName: "Tom Beckett", phone: "+44 114 000 0004", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(30) as never },
];

export const MOCK_LEADS: Lead[] = [
  { id: "lead-1", firstName: "Sarah", lastName: "Jenkins", email: "sarah.j@email.com", phone: "07700 900100", source: "website", status: "active", currentStageId: "new_enquiry", assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "1-3-months", propertyValue: 225000, depositAmount: 25000, loanAmount: 200000, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: hoursAgo(4) as never, updatedAt: hoursAgo(4) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-2", firstName: "James", lastName: "Whitworth", email: "james.w@email.com", phone: "07700 900101", source: "referral", status: "active", currentStageId: "initial_contact", assignedTo: "demo-sales", mortgageType: "remortgage", readiness: "ready-now", propertyValue: 320000, depositAmount: null, loanAmount: 240000, nextFollowUpDate: null, followUpReason: "Rate review due", followUpNotes: null, tags: [], referredBy: "Dave Morris", importId: null, createdAt: daysAgo(3) as never, updatedAt: daysAgo(1) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-3", firstName: "Amira", lastName: "Hassan", email: "amira.h@email.com", phone: "07700 900102", source: "phone", status: "active", currentStageId: "not_ready_yet", assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "6-12-months", propertyValue: null, depositAmount: 15000, loanAmount: null, nextFollowUpDate: daysAgo(-30) as never, followUpReason: "Saving deposit — check in January", followUpNotes: "Wants to buy near Ecclesall Road", tags: ["first-time"], referredBy: null, importId: null, createdAt: daysAgo(14) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-4", firstName: "Mark", lastName: "Taylor", email: "mark.t@email.com", phone: "07700 900103", source: "mab-import", status: "active", currentStageId: "nurturing", assignedTo: "user-3", mortgageType: "buy-to-let", readiness: "3-6-months", propertyValue: 185000, depositAmount: 46000, loanAmount: 139000, nextFollowUpDate: daysAgo(-14) as never, followUpReason: "Awaiting property survey", followUpNotes: null, tags: ["btl"], referredBy: null, importId: "imp-1", createdAt: daysAgo(21) as never, updatedAt: daysAgo(5) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-5", firstName: "Rachel", lastName: "Cooper", email: "rachel.c@email.com", phone: "07700 900104", source: "website", status: "active", currentStageId: "ready_to_proceed", assignedTo: "user-3", mortgageType: "first-time-buyer", readiness: "ready-now", propertyValue: 195000, depositAmount: 20000, loanAmount: 175000, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(30) as never, updatedAt: daysAgo(1) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-6", firstName: "David", lastName: "Chen", email: "david.c@email.com", phone: "07700 900105", source: "referral", status: "converted", currentStageId: "referred_to_mab", assignedTo: "demo-sales", mortgageType: "remortgage", readiness: "ready-now", propertyValue: 410000, depositAmount: null, loanAmount: 280000, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: "Sarah Jenkins", importId: null, createdAt: daysAgo(45) as never, updatedAt: daysAgo(7) as never, convertedAt: daysAgo(7) as never, lostAt: null, lostReason: null },
  { id: "lead-7", firstName: "Emma", lastName: "Wilson", email: "emma.w@email.com", phone: "07700 900106", source: "walk-in", status: "active", currentStageId: "new_enquiry", assignedTo: "user-4", mortgageType: "self-employed", readiness: "exploring", propertyValue: null, depositAmount: null, loanAmount: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: "Self-employed 2 years, needs accounts", tags: ["self-employed"], referredBy: null, importId: null, createdAt: hoursAgo(6) as never, updatedAt: hoursAgo(6) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-8", firstName: "Chris", lastName: "Moore", email: null, phone: "07700 900107", source: "phone", status: "active", currentStageId: "initial_contact", assignedTo: "user-4", mortgageType: "remortgage", readiness: "1-3-months", propertyValue: 275000, depositAmount: null, loanAmount: 200000, nextFollowUpDate: null, followUpReason: "Existing deal expires March", followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(5) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-9", firstName: "Lisa", lastName: "Brown", email: "lisa.b@email.com", phone: "07700 900108", source: "social", status: "active", currentStageId: "nurturing", assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "3-6-months", propertyValue: 180000, depositAmount: 18000, loanAmount: 162000, nextFollowUpDate: daysAgo(-7) as never, followUpReason: "Following up on mortgage options", followUpNotes: null, tags: ["first-time"], referredBy: null, importId: null, createdAt: daysAgo(28) as never, updatedAt: daysAgo(3) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-10", firstName: "Robert", lastName: "Shaw", email: "rob.s@email.com", phone: "07700 900109", source: "mab-import", status: "lost", currentStageId: "not_ready_yet", assignedTo: "user-3", mortgageType: "buy-to-let", readiness: "exploring", propertyValue: null, depositAmount: null, loanAmount: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: "imp-1", createdAt: daysAgo(40) as never, updatedAt: daysAgo(10) as never, convertedAt: null, lostAt: daysAgo(10) as never, lostReason: "No longer interested" },
  { id: "lead-11", firstName: "Hannah", lastName: "Clarke", email: "hannah.c@email.com", phone: "07700 900110", source: "website", status: "converted", currentStageId: "referred_to_mab", assignedTo: "user-4", mortgageType: "first-time-buyer", readiness: "ready-now", propertyValue: 210000, depositAmount: 22000, loanAmount: 188000, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(60) as never, updatedAt: daysAgo(15) as never, convertedAt: daysAgo(15) as never, lostAt: null, lostReason: null },
  { id: "lead-12", firstName: "Yusuf", lastName: "Khan", email: "yusuf.k@email.com", phone: "07700 900111", source: "referral", status: "active", currentStageId: "not_ready_yet", assignedTo: "user-3", mortgageType: "first-time-buyer", readiness: "6-12-months", propertyValue: null, depositAmount: 10000, loanAmount: null, nextFollowUpDate: daysAgo(-60) as never, followUpReason: "Building deposit — review in 6 months", followUpNotes: null, tags: ["first-time"], referredBy: "Mark Taylor", importId: null, createdAt: daysAgo(35) as never, updatedAt: daysAgo(8) as never, convertedAt: null, lostAt: null, lostReason: null },
];

export const MOCK_TASKS: Task[] = [
  { id: "task-1", leadId: "lead-2", assignedTo: "demo-sales", createdBy: "demo-manager", title: "Call James re: rate review", description: "His current deal expires soon, discuss remortgage options", dueDate: now as never, priority: "high", status: "pending", reminderEmails: ["della@mallardmortgages.co.uk"], reminderSent: false, createdAt: daysAgo(1) as never },
  { id: "task-2", leadId: "lead-9", assignedTo: "demo-sales", createdBy: "demo-sales", title: "Send Lisa mortgage comparison", description: null, dueDate: now as never, priority: "normal", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(3) as never },
  { id: "task-3", leadId: "lead-3", assignedTo: "demo-sales", createdBy: "demo-manager", title: "Check in with Amira on deposit savings", description: "She wanted to buy near Ecclesall Road", dueDate: daysAgo(-1) as never, priority: "normal", status: "pending", reminderEmails: ["della@mallardmortgages.co.uk"], reminderSent: false, createdAt: daysAgo(14) as never },
  { id: "task-4", leadId: "lead-4", assignedTo: "user-3", createdBy: "user-3", title: "Follow up on Mark's property survey", description: null, dueDate: now as never, priority: "normal", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(5) as never },
  { id: "task-5", leadId: "lead-8", assignedTo: "user-4", createdBy: "user-4", title: "Call Chris about existing deal expiry", description: null, dueDate: daysAgo(1) as never, priority: "high", status: "pending", reminderEmails: [], reminderSent: true, createdAt: daysAgo(3) as never },
  { id: "task-6", leadId: "lead-5", assignedTo: "user-3", createdBy: "demo-manager", title: "Prepare Rachel's application docs", description: "She's ready to proceed — get DIP sorted", dueDate: daysAgo(-2) as never, priority: "urgent", status: "pending", reminderEmails: ["della@mallardmortgages.co.uk"], reminderSent: false, createdAt: daysAgo(2) as never },
];

export const MOCK_ACTIVITIES: Activity[] = [
  { id: "act-1", leadId: "lead-1", performedBy: "demo-sales", activityType: "note", title: "Sarah Jenkins", description: "Initial enquiry from website — first-time buyer, looking at S11 area", metadata: null, createdAt: hoursAgo(4) as never },
  { id: "act-2", leadId: "lead-2", performedBy: "demo-sales", activityType: "call", title: "James Whitworth", description: "Discussed remortgage options, current deal expires in 8 weeks", metadata: null, createdAt: hoursAgo(6) as never },
  { id: "act-3", leadId: "lead-5", performedBy: "user-3", activityType: "stage-change", title: "Rachel Cooper", description: "Moved from Nurturing to Ready to Proceed", metadata: { from: "nurturing", to: "ready_to_proceed" }, createdAt: daysAgo(1) as never },
  { id: "act-4", leadId: "lead-3", performedBy: "demo-sales", activityType: "email", title: "Amira Hassan", description: "Sent info pack on Help to Buy options", metadata: null, createdAt: daysAgo(2) as never },
  { id: "act-5", leadId: "lead-4", performedBy: "user-3", activityType: "call", title: "Mark Taylor", description: "Property survey delayed — will chase agent", metadata: null, createdAt: daysAgo(3) as never },
  { id: "act-6", leadId: "lead-6", performedBy: "demo-sales", activityType: "stage-change", title: "David Chen", description: "Moved to Referred to MAB — application submitted", metadata: { from: "ready_to_proceed", to: "referred_to_mab" }, createdAt: daysAgo(7) as never },
  { id: "act-7", leadId: "lead-7", performedBy: "user-4", activityType: "meeting", title: "Emma Wilson", description: "Walk-in meeting — self-employed, needs 2 years of accounts", metadata: null, createdAt: hoursAgo(6) as never },
  { id: "act-8", leadId: "lead-9", performedBy: "demo-sales", activityType: "whatsapp", title: "Lisa Brown", description: "Shared mortgage calculator link", metadata: null, createdAt: daysAgo(3) as never },
];

export function isDemoUser(userId: string): boolean {
  return userId.startsWith("demo-");
}
