// Acme Mortgages — generic balanced demo tenant. Used for cold demos when
// the prospect doesn't fit the FTB-heavy or HNW profiles. No regional skew.

import type { Lead, Task, Activity, User, Cadence, Template, CadenceEnrollment } from "@/types";
import { buildSeededCadences, SEEDED_TEMPLATES, buildSeededEnrollments } from "./cadences-seed";

const TENANT_ID = "acme";
const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);
const hoursAgo = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);

export const users: User[] = [
  { id: "demo-manager", tenantId: TENANT_ID, email: "sam@acmemortgages.co.uk", fullName: "Sam Carter", phone: "+44 161 000 0001", role: "manager", avatarUrl: null, isActive: true, createdAt: daysAgo(120) as never },
  { id: "demo-sales", tenantId: TENANT_ID, email: "riley@acmemortgages.co.uk", fullName: "Riley Blake", phone: "+44 161 000 0002", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(80) as never },
  { id: "acme-3", tenantId: TENANT_ID, email: "jordan@acmemortgages.co.uk", fullName: "Jordan Reeves", phone: "+44 161 000 0003", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(50) as never },
  { id: "acme-4", tenantId: TENANT_ID, email: "casey@acmemortgages.co.uk", fullName: "Casey Murphy", phone: "+44 161 000 0004", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(35) as never },
];

export const leads: Lead[] = [
  { id: "lead-acme-1", firstName: "Daniel", lastName: "Foster", email: "d.foster@email.com", phone: "07700 920001", source: "website", status: "active", currentStageId: "new_enquiry", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "1-3-months", propertyValue: 240000, depositAmount: 28000, loanAmount: 212000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: hoursAgo(5) as never, updatedAt: hoursAgo(5) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-acme-2", firstName: "Megan", lastName: "Reed", email: "m.reed@email.com", phone: "07700 920002", source: "referral", status: "active", currentStageId: "initial_contact", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "remortgage", readiness: "ready-now", propertyValue: 295000, depositAmount: null, loanAmount: 210000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: "Deal expires in 6 weeks", followUpNotes: null, tags: [], referredBy: "Old client", importId: null, createdAt: daysAgo(4) as never, updatedAt: daysAgo(1) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-acme-3", firstName: "Owen", lastName: "Bennett", email: "o.bennett@email.com", phone: "07700 920003", source: "phone", status: "active", currentStageId: "not_ready_yet", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "6-12-months", propertyValue: null, depositAmount: 12000, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-45) as never, followUpReason: "Saving deposit", followUpNotes: "Aiming for £20k", tags: ["first-time"], referredBy: null, importId: null, createdAt: daysAgo(20) as never, updatedAt: daysAgo(3) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-acme-4", firstName: "Charlotte", lastName: "Bell", email: "c.bell@email.com", phone: "07700 920004", source: "mab-import", status: "active", currentStageId: "nurturing", currentStageEnteredAt: null, assignedTo: "acme-3", mortgageType: "buy-to-let", readiness: "3-6-months", propertyValue: 220000, depositAmount: 55000, loanAmount: 165000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-7) as never, followUpReason: "BTL purchase progressing", followUpNotes: null, tags: ["btl"], referredBy: null, importId: "imp-acme-1", createdAt: daysAgo(28) as never, updatedAt: daysAgo(6) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-acme-5", firstName: "Nathan", lastName: "Webb", email: "n.webb@email.com", phone: "07700 920005", source: "website", status: "active", currentStageId: "ready_to_proceed", currentStageEnteredAt: null, assignedTo: "acme-3", mortgageType: "first-time-buyer", readiness: "ready-now", propertyValue: 215000, depositAmount: 25000, loanAmount: 190000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(35) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-acme-6", firstName: "Sophie", lastName: "Allen", email: "s.allen@email.com", phone: "07700 920006", source: "referral", status: "converted", currentStageId: "referred_to_mab", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "remortgage", readiness: "ready-now", propertyValue: 365000, depositAmount: null, loanAmount: 245000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: "Megan Reed", importId: null, createdAt: daysAgo(50) as never, updatedAt: daysAgo(8) as never, convertedAt: daysAgo(8) as never, lostAt: null, lostReason: null },
  { id: "lead-acme-7", firstName: "Thomas", lastName: "Hughes", email: "t.hughes@email.com", phone: "07700 920007", source: "walk-in", status: "active", currentStageId: "new_enquiry", currentStageEnteredAt: null, assignedTo: "acme-4", mortgageType: "self-employed", readiness: "exploring", propertyValue: null, depositAmount: null, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: "Self-employed contractor, 18 months trading", tags: ["self-employed"], referredBy: null, importId: null, createdAt: hoursAgo(8) as never, updatedAt: hoursAgo(8) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-acme-8", firstName: "Anna", lastName: "Patel", email: null, phone: "07700 920008", source: "phone", status: "active", currentStageId: "initial_contact", currentStageEnteredAt: null, assignedTo: "acme-4", mortgageType: "remortgage", readiness: "1-3-months", propertyValue: 245000, depositAmount: null, loanAmount: 180000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: "Deal expires April", followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(6) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-acme-9", firstName: "Joshua", lastName: "Knight", email: "j.knight@email.com", phone: "07700 920009", source: "social", status: "active", currentStageId: "nurturing", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "3-6-months", propertyValue: 195000, depositAmount: 19500, loanAmount: 175500, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-10) as never, followUpReason: "Following up on options", followUpNotes: null, tags: ["first-time"], referredBy: null, importId: null, createdAt: daysAgo(30) as never, updatedAt: daysAgo(4) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-acme-10", firstName: "Ellie", lastName: "Ward", email: "e.ward@email.com", phone: "07700 920010", source: "mab-import", status: "lost", currentStageId: "not_ready_yet", currentStageEnteredAt: null, assignedTo: "acme-3", mortgageType: "buy-to-let", readiness: "exploring", propertyValue: null, depositAmount: null, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: "imp-acme-1", createdAt: daysAgo(45) as never, updatedAt: daysAgo(12) as never, convertedAt: null, lostAt: daysAgo(12) as never, lostReason: "Decided to wait" },
  { id: "lead-acme-11", firstName: "Ben", lastName: "Roberts", email: "b.roberts@email.com", phone: "07700 920011", source: "website", status: "converted", currentStageId: "referred_to_mab", currentStageEnteredAt: null, assignedTo: "acme-4", mortgageType: "first-time-buyer", readiness: "ready-now", propertyValue: 230000, depositAmount: 24000, loanAmount: 206000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(70) as never, updatedAt: daysAgo(18) as never, convertedAt: daysAgo(18) as never, lostAt: null, lostReason: null },
  { id: "lead-acme-12", firstName: "Lucy", lastName: "Mitchell", email: "l.mitchell@email.com", phone: "07700 920012", source: "referral", status: "active", currentStageId: "not_ready_yet", currentStageEnteredAt: null, assignedTo: "acme-3", mortgageType: "first-time-buyer", readiness: "6-12-months", propertyValue: null, depositAmount: 8000, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-90) as never, followUpReason: "Building deposit — review in 3 months", followUpNotes: null, tags: ["first-time"], referredBy: "Charlotte Bell", importId: null, createdAt: daysAgo(40) as never, updatedAt: daysAgo(10) as never, convertedAt: null, lostAt: null, lostReason: null },
];

export const tasks: Task[] = [
  { id: "task-acme-1", leadId: "lead-acme-2", assignedTo: "demo-sales", createdBy: "demo-manager", title: "Megan Reed — call about deal expiry", description: "6 weeks until current deal expires", dueDate: now as never, priority: "high", status: "pending", reminderEmails: ["sam@acmemortgages.co.uk"], reminderSent: false, createdAt: daysAgo(1) as never },
  { id: "task-acme-2", leadId: "lead-acme-3", assignedTo: "demo-sales", createdBy: "demo-sales", title: "Owen Bennett — quarterly deposit check-in", description: null, dueDate: daysAgo(-3) as never, priority: "normal", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(20) as never },
  { id: "task-acme-3", leadId: "lead-acme-4", assignedTo: "acme-3", createdBy: "acme-3", title: "Charlotte Bell — chase BTL valuation", description: null, dueDate: now as never, priority: "normal", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(7) as never },
  { id: "task-acme-4", leadId: "lead-acme-5", assignedTo: "acme-3", createdBy: "demo-manager", title: "Nathan Webb — DIP submission", description: "Ready to proceed", dueDate: daysAgo(-1) as never, priority: "urgent", status: "pending", reminderEmails: ["sam@acmemortgages.co.uk"], reminderSent: false, createdAt: daysAgo(2) as never },
  { id: "task-acme-5", leadId: "lead-acme-9", assignedTo: "demo-sales", createdBy: "demo-sales", title: "Joshua Knight — send mortgage comparison", description: null, dueDate: now as never, priority: "normal", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(4) as never },
  { id: "task-acme-6", leadId: "lead-acme-12", assignedTo: "acme-3", createdBy: "demo-manager", title: "Lucy Mitchell — quarterly check-in", description: null, dueDate: daysAgo(-90) as never, priority: "low", status: "pending", reminderEmails: ["sam@acmemortgages.co.uk"], reminderSent: false, createdAt: daysAgo(40) as never },
];

export const cadences: Cadence[] = buildSeededCadences();
export const templates: Template[] = SEEDED_TEMPLATES;

export const enrollments: CadenceEnrollment[] = buildSeededEnrollments({
  "cad-1": ["lead-acme-3", "lead-acme-12"],
  "cad-2": ["lead-acme-2"],
});

export const activities: Activity[] = [
  { id: "act-acme-1", leadId: "lead-acme-1", performedBy: "demo-sales", activityType: "note", title: "Daniel Foster", description: "Website enquiry — first-time buyer with 28k deposit", metadata: null, createdAt: hoursAgo(5) as never },
  { id: "act-acme-2", leadId: "lead-acme-2", performedBy: "demo-sales", activityType: "call", title: "Megan Reed", description: "Discussed remortgage options, deal expires in 6 weeks", metadata: null, createdAt: hoursAgo(10) as never },
  { id: "act-acme-3", leadId: "lead-acme-5", performedBy: "acme-3", activityType: "stage-change", title: "Nathan Webb", description: "Moved from Nurturing to Ready to Proceed", metadata: { from: "nurturing", to: "ready_to_proceed" }, createdAt: daysAgo(2) as never },
  { id: "act-acme-4", leadId: "lead-acme-3", performedBy: "demo-sales", activityType: "email", title: "Owen Bennett", description: "Sent deposit-saving tips and Lifetime ISA info", metadata: null, createdAt: daysAgo(3) as never },
  { id: "act-acme-5", leadId: "lead-acme-4", performedBy: "acme-3", activityType: "call", title: "Charlotte Bell", description: "Property valuation booked for next week", metadata: null, createdAt: daysAgo(4) as never },
  { id: "act-acme-6", leadId: "lead-acme-6", performedBy: "demo-sales", activityType: "stage-change", title: "Sophie Allen", description: "Moved to Referred to MAB", metadata: { from: "ready_to_proceed", to: "referred_to_mab" }, createdAt: daysAgo(8) as never },
  { id: "act-acme-7", leadId: "lead-acme-7", performedBy: "acme-4", activityType: "meeting", title: "Thomas Hughes", description: "Walk-in — self-employed contractor, gathering paperwork", metadata: null, createdAt: hoursAgo(8) as never },
  { id: "act-acme-8", leadId: "lead-acme-9", performedBy: "demo-sales", activityType: "whatsapp", title: "Joshua Knight", description: "Sent calculator link", metadata: null, createdAt: daysAgo(4) as never },
];
