// Friends Capital — high-net-worth / BTL portfolio / equity-release demo tenant.
// London / Surrey property values, longer cases, partner-led firm.

import type { Lead, Task, Activity, User, Cadence, Template, CadenceEnrollment } from "@/types";
import { buildSeededCadences, SEEDED_TEMPLATES, buildSeededEnrollments } from "./cadences-seed";

const TENANT_ID = "friends-capital";
const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);
const hoursAgo = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);

export const users: User[] = [
  { id: "demo-manager", tenantId: TENANT_ID, email: "charlotte@friendscapital.co.uk", fullName: "Charlotte Pemberton", phone: "+44 20 7000 0001", role: "manager", avatarUrl: null, isActive: true, createdAt: daysAgo(180) as never },
  { id: "demo-sales", tenantId: TENANT_ID, email: "marcus@friendscapital.co.uk", fullName: "Marcus Whitley", phone: "+44 20 7000 0002", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(120) as never },
  { id: "fc-3", tenantId: TENANT_ID, email: "sophia@friendscapital.co.uk", fullName: "Sophia Asante", phone: "+44 20 7000 0003", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(90) as never },
  { id: "fc-4", tenantId: TENANT_ID, email: "henry@friendscapital.co.uk", fullName: "Henry Bishop", phone: "+44 20 7000 0004", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(60) as never },
];

export const leads: Lead[] = [
  { id: "lead-fc-1", firstName: "Edward", lastName: "Ashworth", email: "edward.a@email.com", phone: "07700 910001", source: "referral", status: "active", currentStageId: "ready_to_proceed", currentStageEnteredAt: null, assignedTo: "demo-manager", mortgageType: "buy-to-let", readiness: "ready-now", propertyValue: 1850000, depositAmount: 750000, loanAmount: 1100000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-2) as never, followUpReason: "Portfolio refinance — 4-property review", followUpNotes: "Wants to consolidate three London BTLs into one facility", tags: ["btl", "portfolio"], referredBy: "Coutts Private", importId: null, createdAt: daysAgo(45) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-2", firstName: "Caroline", lastName: "Devereux", email: "c.devereux@email.com", phone: "07700 910002", source: "referral", status: "active", currentStageId: "nurturing", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "remortgage", readiness: "3-6-months", propertyValue: 2400000, depositAmount: null, loanAmount: 1200000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-14) as never, followUpReason: "5-yr fix coming off in October", followUpNotes: "Surrey home, wants offset facility this time", tags: ["hnw"], referredBy: "James & Sons", importId: null, createdAt: daysAgo(60) as never, updatedAt: daysAgo(5) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-3", firstName: "Geoffrey", lastName: "Holloway", email: "g.holloway@email.com", phone: "07700 910003", source: "phone", status: "active", currentStageId: "not_ready_yet", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "other", readiness: "6-12-months", propertyValue: 1100000, depositAmount: null, loanAmount: 380000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-90) as never, followUpReason: "Equity release — exploring options post-72nd birthday", followUpNotes: "Wants to gift deposit to grandchildren", tags: ["equity-release"], referredBy: "Wealth Partners", importId: null, createdAt: daysAgo(30) as never, updatedAt: daysAgo(10) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-4", firstName: "Olivia", lastName: "Fairchild", email: "olivia.f@email.com", phone: "07700 910004", source: "website", status: "active", currentStageId: "initial_contact", currentStageEnteredAt: null, assignedTo: "fc-3", mortgageType: "buy-to-let", readiness: "1-3-months", propertyValue: 680000, depositAmount: 200000, loanAmount: 480000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: "First BTL — Bristol student let", followUpNotes: null, tags: ["btl", "first-btl"], referredBy: null, importId: null, createdAt: daysAgo(7) as never, updatedAt: daysAgo(1) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-5", firstName: "Sebastian", lastName: "Marlowe", email: "seb.m@email.com", phone: "07700 910005", source: "referral", status: "converted", currentStageId: "referred_to_mab", currentStageEnteredAt: null, assignedTo: "demo-manager", mortgageType: "remortgage", readiness: "ready-now", propertyValue: 3200000, depositAmount: null, loanAmount: 1800000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: ["hnw"], referredBy: "Caroline Devereux", importId: null, createdAt: daysAgo(90) as never, updatedAt: daysAgo(20) as never, convertedAt: daysAgo(20) as never, lostAt: null, lostReason: null },
  { id: "lead-fc-6", firstName: "Isabella", lastName: "Quincey", email: "i.quincey@email.com", phone: "07700 910006", source: "website", status: "active", currentStageId: "new_enquiry", currentStageEnteredAt: null, assignedTo: "fc-3", mortgageType: "first-time-buyer", readiness: "1-3-months", propertyValue: 1250000, depositAmount: 500000, loanAmount: 750000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: "Notting Hill — buying with parental gift", tags: ["ftb-hnw"], referredBy: null, importId: null, createdAt: hoursAgo(3) as never, updatedAt: hoursAgo(3) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-7", firstName: "Theodore", lastName: "Vance", email: "t.vance@email.com", phone: "07700 910007", source: "phone", status: "active", currentStageId: "nurturing", currentStageEnteredAt: null, assignedTo: "fc-4", mortgageType: "self-employed", readiness: "3-6-months", propertyValue: 950000, depositAmount: 280000, loanAmount: 670000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-21) as never, followUpReason: "Awaiting 3rd-yr accounts", followUpNotes: "Tech founder, recently exited", tags: ["self-employed", "hnw"], referredBy: null, importId: null, createdAt: daysAgo(40) as never, updatedAt: daysAgo(8) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-8", firstName: "Beatrice", lastName: "Langford", email: "b.langford@email.com", phone: "07700 910008", source: "referral", status: "active", currentStageId: "ready_to_proceed", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "buy-to-let", readiness: "ready-now", propertyValue: 590000, depositAmount: 150000, loanAmount: 440000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-1) as never, followUpReason: "BTL purchase — Manchester", followUpNotes: "Limited company structure", tags: ["btl", "ltd-co"], referredBy: "Edward Ashworth", importId: null, createdAt: daysAgo(20) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-9", firstName: "Felix", lastName: "Goodwin", email: "f.goodwin@email.com", phone: "07700 910009", source: "social", status: "active", currentStageId: "not_ready_yet", currentStageEnteredAt: null, assignedTo: "fc-4", mortgageType: "remortgage", readiness: "6-12-months", propertyValue: 1450000, depositAmount: null, loanAmount: 850000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-180) as never, followUpReason: "Current 5-yr fix runs to next March", followUpNotes: "Discussed at networking event", tags: ["remortgage-future"], referredBy: null, importId: null, createdAt: daysAgo(50) as never, updatedAt: daysAgo(15) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-10", firstName: "Antonia", lastName: "Cresswell", email: "a.cresswell@email.com", phone: "07700 910010", source: "website", status: "lost", currentStageId: "nurturing", currentStageEnteredAt: null, assignedTo: "fc-3", mortgageType: "buy-to-let", readiness: "exploring", propertyValue: 320000, depositAmount: null, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(70) as never, updatedAt: daysAgo(20) as never, convertedAt: null, lostAt: daysAgo(20) as never, lostReason: "Went direct to high-street lender" },
  { id: "lead-fc-11", firstName: "Rupert", lastName: "Hawkesbury", email: "r.hawkesbury@email.com", phone: "07700 910011", source: "referral", status: "active", currentStageId: "initial_contact", currentStageEnteredAt: null, assignedTo: "demo-manager", mortgageType: "remortgage", readiness: "1-3-months", propertyValue: 2750000, depositAmount: null, loanAmount: 1400000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: "Fixed-rate maturity", followUpNotes: null, tags: ["hnw"], referredBy: "Caroline Devereux", importId: null, createdAt: daysAgo(8) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null },
  { id: "lead-fc-12", firstName: "Daphne", lastName: "Sutherland", email: "d.sutherland@email.com", phone: "07700 910012", source: "phone", status: "active", currentStageId: "not_ready_yet", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "other", readiness: "6-12-months", propertyValue: 825000, depositAmount: null, loanAmount: 200000, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-120) as never, followUpReason: "Equity release — discussion deferred to next year", followUpNotes: "Spouse hesitant; revisit Q2", tags: ["equity-release"], referredBy: null, importId: null, createdAt: daysAgo(25) as never, updatedAt: daysAgo(11) as never, convertedAt: null, lostAt: null, lostReason: null },
];

export const tasks: Task[] = [
  { id: "task-fc-1", leadId: "lead-fc-1", assignedTo: "demo-manager", createdBy: "demo-manager", title: "Edward Ashworth — portfolio review meeting", description: "4-property refinance, prep summary deck", dueDate: now as never, priority: "high", status: "pending", reminderEmails: ["charlotte@friendscapital.co.uk"], reminderSent: false, createdAt: daysAgo(2) as never },
  { id: "task-fc-2", leadId: "lead-fc-2", assignedTo: "demo-sales", createdBy: "demo-manager", title: "Caroline Devereux — gather offset product list", description: "5-yr fix maturing, she asked for offset options", dueDate: now as never, priority: "high", status: "pending", reminderEmails: ["charlotte@friendscapital.co.uk"], reminderSent: false, createdAt: daysAgo(5) as never },
  { id: "task-fc-3", leadId: "lead-fc-3", assignedTo: "demo-sales", createdBy: "demo-manager", title: "Geoffrey — equity release follow-up", description: "He turns 72 next month, gift to grandchildren", dueDate: daysAgo(-30) as never, priority: "normal", status: "pending", reminderEmails: ["charlotte@friendscapital.co.uk"], reminderSent: false, createdAt: daysAgo(60) as never },
  { id: "task-fc-4", leadId: "lead-fc-7", assignedTo: "fc-4", createdBy: "demo-manager", title: "Theodore — chase 3rd-yr accounts", description: "Need SA302 by end of quarter", dueDate: daysAgo(-1) as never, priority: "normal", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(14) as never },
  { id: "task-fc-5", leadId: "lead-fc-8", assignedTo: "demo-sales", createdBy: "demo-sales", title: "Beatrice — DIP for Manchester BTL", description: "Limited company structure", dueDate: now as never, priority: "high", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(2) as never },
  { id: "task-fc-6", leadId: "lead-fc-11", assignedTo: "demo-manager", createdBy: "demo-manager", title: "Rupert Hawkesbury — initial fact-find", description: "First call after Caroline's referral", dueDate: daysAgo(-2) as never, priority: "urgent", status: "pending", reminderEmails: ["charlotte@friendscapital.co.uk"], reminderSent: false, createdAt: daysAgo(3) as never },
];

export const cadences: Cadence[] = buildSeededCadences();
export const templates: Template[] = SEEDED_TEMPLATES;

// HNW firm — fewer auto-enrollments, mostly manual cadence runs.
export const enrollments: CadenceEnrollment[] = buildSeededEnrollments({
  "cad-2": ["lead-fc-2", "lead-fc-9", "lead-fc-11"], // Caroline, Felix, Rupert — remortgage warm-ups
  "cad-3": ["lead-fc-3", "lead-fc-12"], // Geoffrey, Daphne — equity-release cold re-engagement
});

export const activities: Activity[] = [
  { id: "act-fc-1", leadId: "lead-fc-1", performedBy: "demo-manager", activityType: "meeting", title: "Edward Ashworth", description: "Portfolio overview meeting at our Mayfair office", metadata: null, createdAt: hoursAgo(8) as never },
  { id: "act-fc-2", leadId: "lead-fc-2", performedBy: "demo-sales", activityType: "call", title: "Caroline Devereux", description: "Discussed offset product preferences and rate appetite", metadata: null, createdAt: daysAgo(1) as never },
  { id: "act-fc-3", leadId: "lead-fc-5", performedBy: "demo-manager", activityType: "stage-change", title: "Sebastian Marlowe", description: "Moved to Referred to MAB — case in progress with lender", metadata: { from: "ready_to_proceed", to: "referred_to_mab" }, createdAt: daysAgo(20) as never },
  { id: "act-fc-4", leadId: "lead-fc-3", performedBy: "demo-sales", activityType: "email", title: "Geoffrey Holloway", description: "Sent equity-release brochure pack", metadata: null, createdAt: daysAgo(4) as never },
  { id: "act-fc-5", leadId: "lead-fc-7", performedBy: "fc-4", activityType: "call", title: "Theodore Vance", description: "Accountant promised SA302 in 2 weeks", metadata: null, createdAt: daysAgo(2) as never },
  { id: "act-fc-6", leadId: "lead-fc-11", performedBy: "demo-manager", activityType: "note", title: "Rupert Hawkesbury", description: "Caroline introduced — Westminster property, fixed-rate maturing", metadata: null, createdAt: hoursAgo(20) as never },
  { id: "act-fc-7", leadId: "lead-fc-6", performedBy: "fc-3", activityType: "note", title: "Isabella Quincey", description: "Notting Hill purchase, 40% deposit from parents", metadata: null, createdAt: hoursAgo(2) as never },
  { id: "act-fc-8", leadId: "lead-fc-12", performedBy: "demo-sales", activityType: "call", title: "Daphne Sutherland", description: "Equity release deferred — spouse uncomfortable, revisit Q2", metadata: null, createdAt: daysAgo(11) as never },
];
