// Mallard Mortgages — Sheffield UK, FTB-heavy demo tenant.
// First-time-buyer skew, deposit-saving cycles, Sheffield postcodes.

import type { Lead, Task, Activity, User, Cadence, Template, CadenceEnrollment } from "@/types";
import { buildSeededCadences, SEEDED_TEMPLATES, buildSeededEnrollments } from "./cadences-seed";

const TENANT_ID = "mallard";
const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);
const hoursAgo = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);

export const users: User[] = [
  { id: "demo-manager", tenantId: TENANT_ID, email: "della@mallardmortgages.co.uk", fullName: "Della Mallard", phone: "+44 114 000 0001", role: "manager", avatarUrl: null, isActive: true, createdAt: daysAgo(90) as never },
  { id: "demo-sales", tenantId: TENANT_ID, email: "alex@mallardmortgages.co.uk", fullName: "Alex Rivera", phone: "+44 114 000 0002", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(60) as never },
  { id: "user-3", tenantId: TENANT_ID, email: "priya@mallardmortgages.co.uk", fullName: "Priya Patel", phone: "+44 114 000 0003", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(45) as never },
  { id: "user-4", tenantId: TENANT_ID, email: "tom@mallardmortgages.co.uk", fullName: "Tom Beckett", phone: "+44 114 000 0004", role: "advisor", avatarUrl: null, isActive: true, createdAt: daysAgo(30) as never },
];

export const leads: Lead[] = [
  { id: "lead-1", firstName: "Sarah", lastName: "Jenkins", email: "sarah.j@email.com", phone: "07700 900100", source: "website", status: "active", currentStageId: "new_enquiry", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "1-3-months", propertyValue: 225000, depositAmount: 25000, amountSaved: null, deposit: null, loanAmount: 200000, dealValue: 1200, estimatedCloseDate: daysAgo(-45) as never, confidence: 30, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: hoursAgo(4) as never, updatedAt: hoursAgo(4) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
  { id: "lead-2", firstName: "James", lastName: "Whitworth", email: "james.w@email.com", phone: "07700 900101", source: "referral", status: "active", currentStageId: "initial_contact", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "remortgage", readiness: "ready-now", propertyValue: 320000, depositAmount: null, amountSaved: null, deposit: null, loanAmount: 240000, dealValue: 1800, estimatedCloseDate: daysAgo(-21) as never, confidence: 65, nextFollowUpDate: null, followUpReason: "Rate review due", followUpNotes: null, tags: [], referredBy: "Dave Morris", importId: null, createdAt: daysAgo(3) as never, updatedAt: daysAgo(1) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
  { id: "lead-3", firstName: "Amira", lastName: "Hassan", email: "amira.h@email.com", phone: "07700 900102", source: "phone", status: "active", currentStageId: "not_ready_yet", currentStageEnteredAt: daysAgo(70) as never, assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "6-12-months", propertyValue: null, depositAmount: 15000, amountSaved: null, deposit: null, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-30) as never, followUpReason: "Saving deposit — check in January", followUpNotes: "Wants to buy near Ecclesall Road", tags: ["first-time"], referredBy: null, importId: null, createdAt: daysAgo(14) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
  { id: "lead-4", firstName: "Mark", lastName: "Taylor", email: "mark.t@email.com", phone: "07700 900103", source: "mab-import", status: "active", currentStageId: "nurturing", currentStageEnteredAt: daysAgo(25) as never, assignedTo: "user-3", mortgageType: "buy-to-let", readiness: "3-6-months", propertyValue: 185000, depositAmount: 46000, amountSaved: null, deposit: null, loanAmount: 139000, dealValue: 950, estimatedCloseDate: daysAgo(-60) as never, confidence: 40, nextFollowUpDate: daysAgo(-14) as never, followUpReason: "Awaiting property survey", followUpNotes: null, tags: ["btl"], referredBy: null, importId: "imp-1", createdAt: daysAgo(21) as never, updatedAt: daysAgo(5) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
  { id: "lead-5", firstName: "Rachel", lastName: "Cooper", email: "rachel.c@email.com", phone: "07700 900104", source: "website", status: "active", currentStageId: "ready_to_proceed", currentStageEnteredAt: daysAgo(16) as never, assignedTo: "user-3", mortgageType: "first-time-buyer", readiness: "ready-now", propertyValue: 195000, depositAmount: 20000, amountSaved: null, deposit: null, loanAmount: 175000, dealValue: 1100, estimatedCloseDate: daysAgo(-7) as never, confidence: 90, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(30) as never, updatedAt: daysAgo(1) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
  { id: "lead-6", firstName: "David", lastName: "Chen", email: "david.c@email.com", phone: "07700 900105", source: "referral", status: "converted", currentStageId: "referred_to_mab", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "remortgage", readiness: "ready-now", propertyValue: 410000, depositAmount: null, amountSaved: null, deposit: null, loanAmount: 280000, dealValue: 2100, estimatedCloseDate: null, confidence: 100, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: "Sarah Jenkins", importId: null, createdAt: daysAgo(45) as never, updatedAt: daysAgo(7) as never, convertedAt: daysAgo(7) as never, lostAt: null, lostReason: null, confidenceAtClose: 100, closedOutcome: "converted" },
  { id: "lead-7", firstName: "Emma", lastName: "Wilson", email: "emma.w@email.com", phone: "07700 900106", source: "walk-in", status: "active", currentStageId: "new_enquiry", currentStageEnteredAt: daysAgo(4) as never, assignedTo: "user-4", mortgageType: "self-employed", readiness: "exploring", propertyValue: null, depositAmount: null, amountSaved: null, deposit: null, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: null, followUpReason: null, followUpNotes: "Self-employed 2 years, needs accounts", tags: ["self-employed"], referredBy: null, importId: null, createdAt: hoursAgo(6) as never, updatedAt: hoursAgo(6) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
  { id: "lead-8", firstName: "Chris", lastName: "Moore", email: null, phone: "07700 900107", source: "phone", status: "active", currentStageId: "initial_contact", currentStageEnteredAt: daysAgo(6) as never, assignedTo: "user-4", mortgageType: "remortgage", readiness: "1-3-months", propertyValue: 275000, depositAmount: null, amountSaved: null, deposit: null, loanAmount: 200000, dealValue: 1500, estimatedCloseDate: daysAgo(-30) as never, confidence: 50, nextFollowUpDate: null, followUpReason: "Existing deal expires March", followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(5) as never, updatedAt: daysAgo(2) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
  { id: "lead-9", firstName: "Lisa", lastName: "Brown", email: "lisa.b@email.com", phone: "07700 900108", source: "social", status: "active", currentStageId: "nurturing", currentStageEnteredAt: null, assignedTo: "demo-sales", mortgageType: "first-time-buyer", readiness: "3-6-months", propertyValue: 180000, depositAmount: 18000, amountSaved: null, deposit: null, loanAmount: 162000, dealValue: 900, estimatedCloseDate: daysAgo(-90) as never, confidence: 35, nextFollowUpDate: daysAgo(-7) as never, followUpReason: "Following up on mortgage options", followUpNotes: null, tags: ["first-time"], referredBy: null, importId: null, createdAt: daysAgo(28) as never, updatedAt: daysAgo(3) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
  { id: "lead-10", firstName: "Robert", lastName: "Shaw", email: "rob.s@email.com", phone: "07700 900109", source: "mab-import", status: "lost", currentStageId: "not_ready_yet", currentStageEnteredAt: null, assignedTo: "user-3", mortgageType: "buy-to-let", readiness: "exploring", propertyValue: null, depositAmount: null, amountSaved: null, deposit: null, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: 45, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: "imp-1", createdAt: daysAgo(40) as never, updatedAt: daysAgo(10) as never, convertedAt: null, lostAt: daysAgo(10) as never, lostReason: "No longer interested", confidenceAtClose: 45, closedOutcome: "lost" },
  { id: "lead-11", firstName: "Hannah", lastName: "Clarke", email: "hannah.c@email.com", phone: "07700 900110", source: "website", status: "converted", currentStageId: "referred_to_mab", currentStageEnteredAt: null, assignedTo: "user-4", mortgageType: "first-time-buyer", readiness: "ready-now", propertyValue: 210000, depositAmount: 22000, amountSaved: null, deposit: null, loanAmount: 188000, dealValue: 1250, estimatedCloseDate: null, confidence: 100, nextFollowUpDate: null, followUpReason: null, followUpNotes: null, tags: [], referredBy: null, importId: null, createdAt: daysAgo(60) as never, updatedAt: daysAgo(15) as never, convertedAt: daysAgo(15) as never, lostAt: null, lostReason: null, confidenceAtClose: 100, closedOutcome: "converted" },
  { id: "lead-12", firstName: "Yusuf", lastName: "Khan", email: "yusuf.k@email.com", phone: "07700 900111", source: "referral", status: "active", currentStageId: "not_ready_yet", currentStageEnteredAt: daysAgo(50) as never, assignedTo: "user-3", mortgageType: "first-time-buyer", readiness: "6-12-months", propertyValue: null, depositAmount: 10000, amountSaved: null, deposit: null, loanAmount: null, dealValue: null, estimatedCloseDate: null, confidence: null, nextFollowUpDate: daysAgo(-60) as never, followUpReason: "Building deposit — review in 6 months", followUpNotes: null, tags: ["first-time"], referredBy: "Mark Taylor", importId: null, createdAt: daysAgo(35) as never, updatedAt: daysAgo(8) as never, convertedAt: null, lostAt: null, lostReason: null, confidenceAtClose: null, closedOutcome: null },
];

export const tasks: Task[] = [
  { id: "task-1", leadId: "lead-2", assignedTo: "demo-sales", createdBy: "demo-manager", title: "Call James re: rate review", description: "His current deal expires soon, discuss remortgage options", dueDate: now as never, priority: "high", status: "pending", reminderEmails: ["della@mallardmortgages.co.uk"], reminderSent: false, createdAt: daysAgo(1) as never },
  { id: "task-2", leadId: "lead-9", assignedTo: "demo-sales", createdBy: "demo-sales", title: "Send Lisa mortgage comparison", description: null, dueDate: now as never, priority: "normal", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(3) as never },
  { id: "task-3", leadId: "lead-3", assignedTo: "demo-sales", createdBy: "demo-manager", title: "Check in with Amira on deposit savings", description: "She wanted to buy near Ecclesall Road", dueDate: daysAgo(-1) as never, priority: "normal", status: "pending", reminderEmails: ["della@mallardmortgages.co.uk"], reminderSent: false, createdAt: daysAgo(14) as never },
  { id: "task-4", leadId: "lead-4", assignedTo: "user-3", createdBy: "user-3", title: "Follow up on Mark's property survey", description: null, dueDate: now as never, priority: "normal", status: "pending", reminderEmails: [], reminderSent: false, createdAt: daysAgo(5) as never },
  { id: "task-5", leadId: "lead-8", assignedTo: "user-4", createdBy: "user-4", title: "Call Chris about existing deal expiry", description: null, dueDate: daysAgo(1) as never, priority: "high", status: "pending", reminderEmails: [], reminderSent: true, createdAt: daysAgo(3) as never },
  { id: "task-6", leadId: "lead-5", assignedTo: "user-3", createdBy: "demo-manager", title: "Prepare Rachel's application docs", description: "She's ready to proceed — get DIP sorted", dueDate: daysAgo(-2) as never, priority: "urgent", status: "pending", reminderEmails: ["della@mallardmortgages.co.uk"], reminderSent: false, createdAt: daysAgo(2) as never },
];

export const cadences: Cadence[] = buildSeededCadences();

export const templates: Template[] = SEEDED_TEMPLATES;

// Mallard skews FTB-heavy, so the FTB cadence (cad-1) has the most active enrollments.
export const enrollments: CadenceEnrollment[] = buildSeededEnrollments({
  "cad-1": ["lead-3", "lead-9", "lead-12"], // Amira, Lisa, Yusuf — FTB nurture
  "cad-2": ["lead-2", "lead-8"], // James, Chris — remortgage warm-ups
  "cad-3": ["lead-10"], // Robert — cold re-engagement
  "cad-7": ["lead-6", "lead-11"], // David, Hannah — post-completion check-in (converted)
  "cad-8": ["lead-5"], // Rachel — document chasing (ready to proceed)
  "cad-10": ["lead-1", "lead-7"], // Sarah, Emma — new enquiry welcome
});

export const activities: Activity[] = [
  { id: "act-1", leadId: "lead-1", performedBy: "demo-sales", activityType: "note", title: "Sarah Jenkins", description: "Initial enquiry from website — first-time buyer, looking at S11 area", metadata: null, createdAt: hoursAgo(4) as never },
  { id: "act-2", leadId: "lead-2", performedBy: "demo-sales", activityType: "call", title: "James Whitworth", description: "Discussed remortgage options, current deal expires in 8 weeks", metadata: null, createdAt: hoursAgo(6) as never },
  { id: "act-3", leadId: "lead-5", performedBy: "user-3", activityType: "stage-change", title: "Rachel Cooper", description: "Moved from Nurturing to Ready to proceed", metadata: { from: "nurturing", to: "ready_to_proceed" }, createdAt: daysAgo(1) as never },
  { id: "act-4", leadId: "lead-3", performedBy: "demo-sales", activityType: "email", title: "Amira Hassan", description: "Sent info pack on Help to Buy options", metadata: null, createdAt: daysAgo(2) as never },
  { id: "act-5", leadId: "lead-4", performedBy: "user-3", activityType: "call", title: "Mark Taylor", description: "Property survey delayed — will chase agent", metadata: null, createdAt: daysAgo(3) as never },
  { id: "act-6", leadId: "lead-6", performedBy: "demo-sales", activityType: "stage-change", title: "David Chen", description: "Moved to Deal Done — application submitted", metadata: { from: "ready_to_proceed", to: "referred_to_mab" }, createdAt: daysAgo(7) as never },
  { id: "act-7", leadId: "lead-7", performedBy: "user-4", activityType: "meeting", title: "Emma Wilson", description: "Walk-in meeting — self-employed, needs 2 years of accounts", metadata: null, createdAt: hoursAgo(6) as never },
  { id: "act-8", leadId: "lead-9", performedBy: "demo-sales", activityType: "whatsapp", title: "Lisa Brown", description: "Shared mortgage calculator link", metadata: null, createdAt: daysAgo(3) as never },
  { id: "act-9", leadId: "lead-4", performedBy: "user-3", activityType: "email", title: "Mark Taylor", description: "Sent BTL product comparison", metadata: null, createdAt: daysAgo(8) as never },
  { id: "act-10", leadId: "lead-8", performedBy: "user-4", activityType: "call", title: "Chris Moore", description: "Discussed existing deal options", metadata: null, createdAt: daysAgo(9) as never },
  { id: "act-11", leadId: "lead-9", performedBy: "demo-sales", activityType: "call", title: "Lisa Brown", description: "Quarterly check-in on mortgage plans", metadata: null, createdAt: daysAgo(9) as never },
  { id: "act-12", leadId: "lead-12", performedBy: "user-3", activityType: "whatsapp", title: "Yusuf Khan", description: "Sent deposit savings progress tracker", metadata: null, createdAt: daysAgo(10) as never },
  { id: "act-13", leadId: "lead-7", performedBy: "user-4", activityType: "email", title: "Emma Wilson", description: "Requested SA302 and accounts", metadata: null, createdAt: daysAgo(11) as never },
  { id: "act-14", leadId: "lead-2", performedBy: "demo-sales", activityType: "note", title: "James Whitworth", description: "Logged rate comparison findings", metadata: null, createdAt: daysAgo(12) as never },
  { id: "act-15", leadId: "lead-3", performedBy: "demo-manager", activityType: "call", title: "Amira Hassan", description: "Checked in on deposit progress", metadata: null, createdAt: daysAgo(10) as never },
];
